### ISSUE TITLE
Add task

### ISSUE THREAD

**Issue by gabrieldelaparra** [gabrieldelaparra/Iteracion-1#1]

**Comment by gabrieldelaparra** [comment]
- [ ] Add Model;
- [ ] Create Controller Logic (POST);
- [ ] Create Add Task View;

**Comment by danieldt** [comment]
Buena cabros!

Cómo les fue con los tests?

**Comment by gabrieldelaparra** [comment]
al final salieron todos los tests.
la vista del listar los task está má rara qe la chochi si, se ven pal lao

**Comment by danieldt** [comment]
Buena, filete!

Igual me parece que la maquetación no es lo más importante por ahora, eso ya sería tema de hacer un buen layout y tener buen CSS. Se puede ver más adelante si el cliente lo pide.
