### ISSUE TITLE
Add AddTask button to Tasks list

### ISSUE THREAD

**Issue by gabrieldelaparra** [gabrieldelaparra/Iteracion-1#4]

**Comment by danieldt** [comment]
@gabrieldelaparra no sé si tienes pensado ver este tema. Si te parece lo puedo ver yo. Ahí me avisas.

**Comment by gabrieldelaparra** [comment]
ya lo hicimos, faltó darle el close en el commit, lo olvidé. De todas formas, el check no funciona :/ (como creo un issue desde acá?)
